### ISSUE TITLE
Is there a reason to not use the "kubernetes" tfstate backend?

### ISSUE THREAD

**Issue by docteurklein** [GalleyBytes/terraform-operator#3]
Hi,
I love the idea behind a terraform CRD (I'm watching this space and just discovered your project).

I'm wondering if there is a reason for not chosing https://www.terraform.io/docs/backends/types/kubernetes.html as a default backend? Is this because of the secret-size limit (1MB) ?

Thanks!

**Comment by isaaguilar** [comment]
I believe that the kubernetes backend is only available with Terraform >= 0.13.0. This project supports >= 0.11.9 (or something like that) so it would make the default backend incompatible with earlier versions.

There is a `customBackend` feature to allow users to specify their own backends. I just tried, however, and it looks like if "kubernetes" backend is selected, the role for the tf-runner needs to be updated to this: 

```yaml
# rbac role rules for the tf-runner pod
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets # needs to be added
  verbs:
  - '*'
# and leases needs to be added
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
```

### limitations

I could see some limitations in the kubernetes backend since it requires Secrets permissions to access tfstate. Hypothetically, If state data needs to be read from another namespace for a certain module, there would be an issue getting access to it.

### solution?

I think I might make some changes to read for `backend "kubernetes"` to add RBAC permissions to the tf-runner.  That would allow someone to use "kubernetes" backend by adding this to the terraform spec:

```
  customBackend: |-
    terraform {
      backend "kubernetes" {
        secret_suffix    = "state"
        in_cluster_config  = true
      }
    }
```
