### ISSUE TITLE
Sources are ambiguous and hard to understand

### ISSUE THREAD

**Issue by isaaguilar** [GalleyBytes/terraform-operator#63]
The `spec.sources[]` array is hard to understand. Is is used to download tfvars? Or templates? Or other `.tf` files that get run as part of my module? 

Rhetorical question... but technically it can be any of those and it is hard to understand the behaviour there. What will probably change soon is that source `extras` will be changed to `options`, and the options that can be used (that I can think of) is `type` which can be either `tfvars` or `tpl`.

So a source may look like:

```yaml
...
spec:
  sources:
  - address: https://github.com/isaaguilar/private-config//simple-aws-modules/test.tfvars
    type: tfvars
 ```

 Another option may be `path`, which would be defined as the relative path from the main module to download the file into.  
  
```yaml
...
spec:
  sources:
  - address: https://github.com/isaaguilar/private-config//simple-aws-modules/test.json.tpl
    type: tpl
    path: templates/test.json.tpl # or maybe just templates/ to keep the same name of the file
 ```

By making these changes, sources becomes less ambiguous and easier to reason about in their execution when the terraform runners get executed. 

Also, `sources` is kind of an odd name for downloaded resources. Another name perhaps?
