### ISSUE TITLE
init pod shows error state and terraform fails to deploy

### ISSUE THREAD

**Issue by dniasoff** [GalleyBytes/terraform-operator#72]
Trying to deploy the following terraform module
```
apiVersion: tf.isaaguilar.com/v1alpha1
kind: Terraform
metadata:
  name: external-dns-service-principal
  namespace: tf-system
spec:
  terraformVersion: 1.0.9
  customBackend: |-
    terraform {
      backend "kubernetes" {
        secret_suffix    = "external-dns-service-principal"
        in_cluster_config  = true
      }
    }
  ignoreDelete: false
  terraformModule: https://github.com/QumulusTechnology/terraform-azure-enterprise-application.git
  credentials:
  - secretNameRef:
      name: azure-session-credentials
  env:
  - name: TF_VAR_name
    value: external-dns-service-principal
```
Getting the following error
Noticed this error in pod logs
```
Initializing the backend...
╷
│ Error: Failed to get existing workspaces: secrets is forbidden: User "system:serviceaccount:tf-system:tf-external-dns-service-principal-bkpnv2rm-v2" cannot list resource "secrets" in API group "" in the namespace "default"
│
```
Thanks for a great project and amazing concept
