### ISSUE TITLE
support env.valueFrom for TF_VAR_ values from Secrets?

### ISSUE THREAD

**Issue by jstrachan** [GalleyBytes/terraform-operator#8]
being able to create [environment variables from secrets is super handy in k8s](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables) - I wonder if we should extend the [EnvVar](https://github.com/isaaguilar/terraform-operator/blob/master/pkg/apis/tf/v1alpha1/terraform_types.go#L46) struct to also support k8s style `valueFrom` too?

So you could populate your TF vars as:

```yaml
apiVersion: tf.isaaguilar.com/v1alpha1
kind: Terraform
metadata:
  name: tf1
spec:
  env:
  - name: TF_VAR_foo
    value: someValue
  - name: TF_VAR_bar
     valueFrom:
       secretKeyRef:
         name: mysecret
         key: token
```

or is there a nicer TF way to inject secret values?
