### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by ahmed-soria** [GalleyBytes/terraform-operator#92]
fatal: unable to access 'https://git.example.local/soria/tfo.git/': SSL certificate problem: self signed certificate in certificate chain

 - I'm trying to connect to my local git which is using self signed certificate and am getting the above error. 
 - I'm using a terraform module to create vmware resources on my local env, I need to know how to skip the ssl verification.

**Comment by isaaguilar** [comment]
Hi @ahmed-soria  Have you tried using the SSH method instead of HTTPS? 

This will be a good topic for a blog article, but I'll try to do a TL;DR;

This is how I would tackle this issue: 

1. Create a k8s secret in your cluster with the private key required to access your private git repo. 

```bash
SECRET_KEY=$(cat ~/.ssh/id_rsa | base64)

cat << EOF | kubectl apply -f -
apiVersion: v1
data:
  id_rsa: $SECRET_KEY
kind: Secret
metadata:
  name: gitsshkey
  namespace: default
type: Opaque
EOF
```

2. Use the `scmAuthMethods` of the terraform operator spec.

```yaml
kind: terraform
spec:
  ...
  scmAuthMethods:
  - host: git.example.local
    git:
      ssh:
        sshKeySecretRef:
          name: gitsshkey       # This is the secret name/key you created in step 1
          key: id_rsa

  terraformModule: git@git.example.local:soria/tfo.git
```

3. Apply the updated manifest

**Comment by ahmed-soria** [comment]
Thank you,  I have tried this and seems good as we got a new error 

error: pathspec 'master' did not match any file(s) known to git

**Comment by isaaguilar** [comment]
The `terraformModule` may need the branch name to use. I'm not sure if the default branch is correctly selected by tfo. 

Try adding a "?ref" to your module:

```yaml
kind: terraform
spec:
    ...
    terraformModule: git@git.example.local:soria/tfo.git?ref=main # or any branch name like ?ref=branch-name
```

I know newer git now defaults to `main` branch.
